<a href="https://colab.research.google.com/github/kasubikila/githubTest/blob/main/%3Cyour_x500%3EHomework7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1** Row Echelon Form and Rank

In [1]:
import numpy as np

# Initialize matrix for test case a) in Problem 1.1
A1_square = np.array([
    [1, 0, 1, 0],
    [0, 0, 0, 0],
    [0, 0, 3, 1],
    [0, 0, 3, 0]
], dtype=np.float64)

# Initialize matrix for test case b) in Problem 1.1
A2_square = np.array([
    [0, 1, 1],
    [2, 6, 4],
    [1, 1, 4]
], dtype=np.float64)

# Display matrices for verification
print("Matrix A1_square:")
print(A1_square)
print("\nMatrix A2_square:")
print(A2_square)


Matrix A1_square:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]

Matrix A2_square:
[[0. 1. 1.]
 [2. 6. 4.]
 [1. 1. 4.]]


**1.1** Row echelon form for square matrices by Gaussian elimination

In [22]:

def GE_square(A, print_flag):
    # Make a copy of A to avoid modifying the original matrix
    R = A.copy()
    n = R.shape[0]  # Number of rows (and columns) in the square matrix
    pvt_list = []  # List to keep track of the pivot rows
    k = 0  # Column index for the pivot element
    eps = np.finfo(np.float32).eps  # Small epsilon value for numerical stability

    # Perform Gaussian Elimination
    for k in range(n):
        # Pivoting: Search for the largest value in the k-th column to use as the pivot
        max_row = np.argmax(np.abs(R[k:n, k])) + k  # Find the max value in column k, starting from row k
        if np.abs(R[max_row, k]) < eps:
            # If the pivot is too small, skip this column (potentially a zero row)
            continue

        # Swap rows if the max element is not the current row
        if max_row != k:
            R[[k, max_row]] = R[[max_row, k]]  # Swap the rows in the matrix
            pvt_list.append(k)  # Add this column index to the pivot list

        # Eliminate the entries below the pivot
        for i in range(k + 1, n):
            if R[i, k] != 0:
                factor = R[i, k] / R[k, k]  # Factor to make the entry below pivot zero
                R[i, k:n] -= factor * R[k, k:n]  # Subtract the appropriate multiple of the pivot row from the current row

    # Check for print flag, if True, display the steps
    if print_flag:
        print("Row echelon form of the matrix:")
        print(R)
        print("Pivot rows:", pvt_list)

    return R, pvt_list


In [23]:
R, pvt_idx_list = GE_square(A1_square, True)
# print out the row echelon form
print("row echelon form of A1_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Row echelon form of the matrix:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Pivot rows: [0]
row echelon form of A1_square:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Indices of pivot values:
[0]


In [24]:
R, pvt_idx_list = GE_square(A2_square, True)
# print out the row echelon form
print("row echelon form of A2_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Row echelon form of the matrix:
[[3.         5.         3.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.        ]]
Pivot rows: [0]
row echelon form of A2_square:
[[3.         5.         3.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.        ]]
Indices of pivot values:
[0]


**1.2**  Row echelon form for rectangular matrices by Gaussian elimination

In [ ]:
#Initializing matrix for test case a) in Problem 1.2
A1_rect = np.array([[1, 2, 2, -1], [4, 8, 9, 6], [0, 3, 2, 9]], dtype=np.float64)

#Initializing matrix for test case b) in Problem 1.2
A2_rect = np.array([[1, 2, 3, 1, 2], [0, 4, 6, 0, 1], [2, 4, 8, 0, 0], [0, 1, 2, 0, 9]], dtype=np.float64)

In [25]:

def GE_rectangular(A, print_steps=False):
    A = A.astype(float)  # Ensure A is of type float
    rows, cols = A.shape
    pvt_idx_list = []  # To store pivot indices

    # Perform Gaussian Elimination for rectangular matrices
    k = 0  # Column index
    for r in range(rows):
        # Check if subvector is zero
        while np.all(A[r:, k] == 0):
            k += 1
            if k == cols:
                # If all the subvectors are zero, we stop early
                print("Final matrix R:")
                print(A)
                print("Pivot indices:", pvt_idx_list)
                return A, pvt_idx_list

        # Find the row with the largest absolute value in column k
        max_row = np.argmax(np.abs(A[r:, k])) + r
        A[[r, max_row]] = A[[max_row, r]]  # Swap rows

        # Record the pivot index
        pvt_idx_list.append(k)

        if print_steps:
            print(f"Step {r+1} - Row echelon form:")
            print(A)

        # Eliminate the rows below the pivot
        for j in range(r+1, rows):
            if A[j, k] != 0:
                factor = A[j, k] / A[r, k]
                A[j, k:] -= factor * A[r, k:]

        if print_steps:
            print(f"After elimination step {r+1}:")
            print(A)

    print("Final row echelon form (R):")
    print(A)
    print("Pivot indices:", pvt_idx_list)

    return A, pvt_idx_list


# Example 1 from the textbook
A1 = np.array([[1, 2, 2, -1],
               [4, 8, 9, 6],
               [0, 3, 2, 9]], dtype=float)

print("Test on Example 1:")
R1, pvt_idx_list1 = GE_rectangular(A1, True)

# Example 2 from the textbook
A2 = np.array([[1, 2, 3, 1, 2],
               [0, 4, 6, 0, 1],
               [2, 4, 8, 0, 0],
               [0, 1, 2, 0, 9]], dtype=float)

print("\nTest on Example 2:")
R2, pvt_idx_list2 = GE_rectangular(A2, True)

# Test on square example (Eq. 3) for debugging
A3 = np.array([[1, 2, 1],
               [2, 4, 2],
               [3, 5, 3]], dtype=float)

print("\nTest on square example (Eq. 3):")
R3, pvt_idx_list3 = GE_rectangular(A3, True)

# Test on another square example (Eq. 4)
A4 = np.array([[1, 3, 2],
               [2, 5, 4],
               [3, 7, 6]], dtype=float)

print("\nTest on square example (Eq. 4):")
R4, pvt_idx_list4 = GE_rectangular(A4, True)


Test on Example 1:
Step 1 - Row echelon form:
[[ 4.  8.  9.  6.]
 [ 1.  2.  2. -1.]
 [ 0.  3.  2.  9.]]
After elimination step 1:
[[ 4.    8.    9.    6.  ]
 [ 0.    0.   -0.25 -2.5 ]
 [ 0.    3.    2.    9.  ]]
Step 2 - Row echelon form:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
After elimination step 2:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Step 3 - Row echelon form:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
After elimination step 3:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Final row echelon form (R):
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Pivot indices: [0, 1, 2]

Test on Example 2:
Step 1 - Row echelon form:
[[2. 4. 8. 0. 0.]
 [0. 4. 6. 0. 1.]
 [1. 2. 3. 1. 2.]
 [0. 1. 2. 0. 9.]]
After elimination step 1:
[[ 2.  4.  8.  0.  0.]
 [ 0.  4.  6.  0.  1.]
 [ 0.  0. -1.  1.  2.]
 [ 0

In [12]:
def GE_rectangular(A, print_flag):
    R = A.copy()  # Create a deep copy of the input matrix A
    n, m = R.shape  # Get the number of rows and columns in A
    pvt_list = []  # List to store pivot indices
    k = 0  # Initialize the column index for pivoting

    # Algorithm implementation...
    for r in range(n):  # Loop over rows
        while (np.all(R[r:, k] == 0)):  # Check if subvector is all-zero
            k += 1
            if k == m:
                return R, pvt_list
        # Find the pivot element in the current column
        i = np.argmax(np.abs(R[r:, k])) + r
        R[[r, i], :] = R[[i, r], :]  # Swap rows
        pvt_list.append(k)  # Add the pivot column index
        for j in range(r + 1, n):  # Eliminate rows below
            λ = R[j, k] / R[r, k]
            R[j, :] -= λ * R[r, :]

    return R, pvt_list  # Return the row echelon form and pivot list


In [13]:

# Define the GE_rectangular function (Gaussian Elimination)
def GE_rectangular(A, print_steps=False):
    A = A.astype(float)  # Ensure A is of type float
    rows, cols = A.shape
    pvt_idx_list = []  # To store pivot indices

    # Perform Gaussian Elimination
    for i in range(min(rows, cols)):
        # Find the pivot row
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if A[max_row, i] == 0:
            continue

        # Swap rows
        A[[i, max_row]] = A[[max_row, i]]
        pvt_idx_list.append(i)

        # Make elements below the pivot equal to zero
        for j in range(i+1, rows):
            if A[j, i] != 0:
                factor = A[j, i] / A[i, i]
                A[j, i:] -= factor * A[i, i:]

        if print_steps:
            print(f"Step {i+1} - Row echelon form:")
            print(A)

    return A, pvt_idx_list

# Example matrix A2_rect
A2_rect = np.array([[1, 2, 3],
                    [2, 4, 5],
                    [3, 6, 7]], dtype=float)

# Call the GE_rectangular function
R, pvt_idx_list = GE_rectangular(A2_rect, True)

# Print out the row echelon form
print("Row echelon form of A2_rect:")
print(R)

# Print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)


Step 1 - Row echelon form:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Step 3 - Row echelon form:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Row echelon form of A2_rect:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Indices of pivot values:
[0, 2]


In [14]:
import numpy as np

# Define the GE_rectangular function (Gaussian Elimination)
def GE_rectangular(A, print_steps=False):
    A = A.astype(float)  # Ensure A is of type float
    rows, cols = A.shape
    pvt_idx_list = []  # To store pivot indices

    # Perform Gaussian Elimination
    for i in range(min(rows, cols)):
        # Find the pivot row
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if A[max_row, i] == 0:
            continue

        # Swap rows
        A[[i, max_row]] = A[[max_row, i]]
        pvt_idx_list.append(i)

        # Make elements below the pivot equal to zero
        for j in range(i+1, rows):
            if A[j, i] != 0:
                factor = A[j, i] / A[i, i]
                A[j, i:] -= factor * A[i, i:]

        if print_steps:
            print(f"Step {i+1} - Row echelon form:")
            print(A)

    return A, pvt_idx_list

# Test matrix A1_square (replace with the actual matrix you want to test)
A1_square = np.array([[1, 2, 3],
                      [2, 4, 5],
                      [3, 6, 7]], dtype=float)

# Call the GE_rectangular function
R, pvt_idx_list = GE_rectangular(A1_square, True)

# Print out the row echelon form
print("Row echelon form of A1_square:")
print(R)

# Print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)


Step 1 - Row echelon form:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Step 3 - Row echelon form:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Row echelon form of A1_square:
[[3.         6.         7.        ]
 [0.         0.         0.33333333]
 [0.         0.         0.66666667]]
Indices of pivot values:
[0, 2]


In [15]:

# Define the GE_rectangular function (Gaussian Elimination)
def GE_rectangular(A, print_steps=False):
    A = A.astype(float)  # Ensure A is of type float
    rows, cols = A.shape
    pvt_idx_list = []  # To store pivot indices

    # Perform Gaussian Elimination
    for i in range(min(rows, cols)):
        # Find the pivot row
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if A[max_row, i] == 0:
            continue

        # Swap rows
        A[[i, max_row]] = A[[max_row, i]]
        pvt_idx_list.append(i)

        # Make elements below the pivot equal to zero
        for j in range(i+1, rows):
            if A[j, i] != 0:
                factor = A[j, i] / A[i, i]
                A[j, i:] -= factor * A[i, i:]

        if print_steps:
            print(f"Step {i+1} - Row echelon form:")
            print(A)

    return A, pvt_idx_list

# Test matrix A2_square (replace with the actual matrix you want to test)
A2_square = np.array([[1, 2, 1],
                      [2, 4, 2],
                      [3, 5, 3]], dtype=float)

# Call the GE_rectangular function
R, pvt_idx_list = GE_rectangular(A2_square, True)

# Print out the row echelon form
print("Row echelon form of A2_square:")
print(R)

# Print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)


Step 1 - Row echelon form:
[[3.         5.         3.        ]
 [0.         0.66666667 0.        ]
 [0.         0.33333333 0.        ]]
Step 2 - Row echelon form:
[[3.         5.         3.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.        ]]
Row echelon form of A2_square:
[[3.         5.         3.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.        ]]
Indices of pivot values:
[0, 1]


**1.3** Matrix rank and number of pivots

In [26]:
from numpy.linalg import matrix_rank

# Re-implement the GE_rectangular function (as in the previous example)
def GE_rectangular(A):
    R = A.copy()  # Deep copy of A to avoid modifying the original matrix
    n, m = R.shape  # Get the number of rows and columns
    pvt_list = []  # List to store pivot indices
    k = 0  # Column index tracker

    for r in range(n):
        while np.all(R[r:n, k] == 0):  # Check if the subvector is all zeros
            k += 1
            if k == m:
                # If we have exhausted all columns, return the current R and pivot list
                return R, pvt_list

        # Find the row with the largest absolute value in column k
        i = np.argmax(np.abs(R[r:n, k])) + r
        # Swap the rows
        R[[r, i], :] = R[[i, r], :]

        # Add the pivot column index to the pivot list
        pvt_list.append(k)

        # Eliminate rows below the pivot row
        for j in range(r+1, n):
            lambda_ = R[j, k] / R[r, k]
            R[j, :] -= lambda_ * R[r, :]

    return R, pvt_list

# Matrices X, Y, Z for testing
X = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 4]], dtype=np.float64)
Y = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 6]], dtype=np.float64)
Z = np.array([[1, 2, 4, 1], [3, 5, 12, 3], [4, 8, 16, 6]], dtype=np.float64)

# Validate the ranks of matrices X, Y, and Z using numpy's matrix_rank function
r_X = matrix_rank(X)
r_Y = matrix_rank(Y)
r_Z = matrix_rank(Z)

# Print the results
print(f"Rank of X (from numpy): {r_X}")
print(f"Rank of Y (from numpy): {r_Y}")
print(f"Rank of Z (from numpy): {r_Z}")

# Function to print REF and rank details
def print_ref_and_rank(A, matrix_name):
    REF, pivots = GE_rectangular(A)
    rank = len(pivots)  # Rank is the number of pivots
    print(f"Reduced Row Echelon Form (RREF) of {matrix_name}:\n{REF}")
    print(f"Pivots in {matrix_name}: {pivots}")
    print(f"Rank of {matrix_name}: {rank}")
    print(f"Numpy's computed rank of {matrix_name}: {matrix_rank(A)}\n")

# Call the function for each matrix X, Y, Z
print_ref_and_rank(X, "X")
print_ref_and_rank(Y, "Y")
print_ref_and_rank(Z, "Z")


Rank of X (from numpy): 1
Rank of Y (from numpy): 2
Rank of Z (from numpy): 3
Reduced Row Echelon Form (RREF) of X:
[[ 4.  8. 16.  4.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Pivots in X: [0]
Rank of X: 1
Numpy's computed rank of X: 1

Reduced Row Echelon Form (RREF) of Y:
[[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.   0. ]]
Pivots in Y: [0, 3]
Rank of Y: 2
Numpy's computed rank of Y: 2

Reduced Row Echelon Form (RREF) of Z:
[[ 4.   8.  16.   6. ]
 [ 0.  -1.   0.  -1.5]
 [ 0.   0.   0.  -0.5]]
Pivots in Z: [0, 1, 3]
Rank of Z: 3
Numpy's computed rank of Z: 3



In [27]:
from numpy.linalg import matrix_rank

# Matrix definitions
X = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 4]], dtype=np.float64)
Y = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 6]], dtype=np.float64)
Z = np.array([[1, 2, 4, 1], [3, 5, 12, 3], [4, 8, 16, 6]], dtype=np.float64)

# Validate ranks using numpy.linalg.matrix_rank
r_X = matrix_rank(X)
r_Y = matrix_rank(Y)
r_Z = matrix_rank(Z)

# Compute nullity (dimension of null space)
nullity_X = X.shape[1] - r_X
nullity_Y = Y.shape[1] - r_Y
nullity_Z = Z.shape[1] - r_Z

# Output the results
print(f"rank(X) = {r_X}, dimension of null(X) = {nullity_X}")
print(f"rank(Y) = {r_Y}, dimension of null(Y) = {nullity_Y}")
print(f"rank(Z) = {r_Z}, dimension of null(Z) = {nullity_Z}")


rank(X) = 1, dimension of null(X) = 3
rank(Y) = 2, dimension of null(Y) = 2
rank(Z) = 3, dimension of null(Z) = 1


**Please double-click here and fill in the rank and dimension of nullspace of the these matrices**

rank(X) = 1, dimension of null(X) = 3

rank(Y) = 2, dimension of null(Y) = 2

rank(Z) = 3, dimension of null(Z) = 1
